---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cicd-app-pb
  template:
    metadata:
      labels:
        app: cicd-app-pb
    spec:
      containers:
      - name: cicd-app-pb
        image: devbrunofernandes/cicd-app-pb:placeholder
        ports:
        - containerPort: 8000

---
---
apiVersion: v1
kind: Service
metadata:
  name: api-app-nodeport
spec:
  type: NodePort
  selector:
    app: cicd-app-pb
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 31000
      protocol: TCP
      
---